
development:
  adapter: postgresql
  encoding: unicode
  database: giftlist_development
  pool: 5
  username: randy2
  password:
  timeout: 5000

  test:
  adapter: postgresql
  encoding: unicode
  database: giftlist_test
  pool: 5
  username: randy2
  password:
  timeout: 5000

