
development:
  adapter: postgresql
  encoding: unicode
  database: db/giftlist_development
  pool: 5
  username: randy2
  password:
  timeout: 5000

  test:
  adapter: postgresql
  encoding: unicode
  database: db/giftlist_test
  pool: 5
  username: randy2
  password:
  timeout: 5000

