# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23ab59fbe119347dd06bc4c4f48ec48d312ffe52d66a1195f5ba670b3d07b677b3ac8d795f32ddbf65f1db175e91bbffcc77313ccb95ca76833fe773f8df6fa

test:
  secret_key_base: 8e1aed3878ddc5b1ad8d4ef26788f2c2b72d56df70a2bbfd4849fc4e663f3ea5edcab2abee1290a8b243b4905e4bfadd41d2149e2326ceaa35d5c3637edac4c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
